# ============================================================
# ALERTA UTEC - SERVERLESS COMPOSE
# ============================================================

org: ${env:ORG_NAME}
app: alerta-utec-backend
stage: dev

# Usar archivo local para el estado
state:
  file: .serverless/state.json

services:
  # Capa compartida con dependencias Python
  dependencias:
    path: Dependencias

  # Infraestructura: Tablas DynamoDB y S3
  infraestructura:
    path: DataGenerator
    dependsOn:
      - dependencias

  # Microservicio de gestión de usuarios
  usuarios:
    path: Usuarios
    dependsOn:
      - dependencias
    hooks:
      before:deploy:deploy:
        - echo "📊 Creando recursos de infraestructura y poblando datos..."
        - cd DataGenerator && python3 DataPoblator.py && cd ..

  # Microservicio de gestión de incidentes
  incidentes:
    path: Incidentes
    dependsOn:
      - dependencias
      - usuarios

  # Microservicio de analítica
  analitica:
    path: Analitica
    dependsOn:
      - dependencias
      - incidentes

