# ============================================================
# ALERTA UTEC - SERVERLESS COMPOSE
# ============================================================

org: ${env:ORG_NAME}
app: alerta-utec-backend
stage: dev

services:
  # Capa compartida con dependencias Python
  dependencias:
    path: Dependencias

  # Infraestructura: Tablas DynamoDB y S3
  infraestructura:
    path: DataGenerator
    dependsOn:
      - dependencias

  # Microservicio de gestión de usuarios
  usuarios:
    path: Usuarios
    dependsOn:
      - dependencias
      - infraestructura

  # Microservicio de gestión de incidentes
  incidentes:
    path: Incidentes
    dependsOn:
      - dependencias
      - infraestructura
      - usuarios

  # Microservicio de analítica
  analitica:
    path: Analitica
    dependsOn:
      - dependencias
      - infraestructura
      - incidentes

