# ============================================================
# ALERTA UTEC - SERVERLESS COMPOSE
# ============================================================

org: ${env:ORG_NAME}
app: alerta-utec-backend
stage: dev

# Usar archivo local para el estado
state:
  file: .serverless/state.json

# Hook global: ejecutar antes de cualquier despliegue
hooks:
  before:deploy:
    - echo "📊 Creando recursos de infraestructura y poblando datos..."
    - chmod +x DataGenerator/run_poblator.sh && DataGenerator/run_poblator.sh
    - echo "✅ Recursos de infraestructura listos"

services:
  # Capa compartida con dependencias Python
  dependencias:
    path: Dependencias

  # Microservicio de gestión de usuarios
  usuarios:
    path: Usuarios
    dependsOn:
      - dependencias

  # Microservicio de gestión de incidentes
  incidentes:
    path: Incidentes
    dependsOn:
      - dependencias
      - usuarios

  # Microservicio de analítica
  analitica:
    path: Analitica
    dependsOn:
      - dependencias
      - incidentes

